# Generated by Django 5.0.4 on 2024-05-27 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_usuario_options_alter_usuario_dni_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntFamiliares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam_cardiovasculares', models.BooleanField(default=False, verbose_name='Cardiovasculares')),
                ('fam_cardiovasculares_cual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cual?')),
                ('fam_neurologicas', models.BooleanField(default=False, verbose_name='Neurológicas')),
                ('fam_neurologicas_cual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cual?')),
                ('fam_tumorales', models.BooleanField(default=False, verbose_name='Tumorales')),
                ('fam_tumorales_cual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cual?')),
                ('fam_respiratorias', models.BooleanField(default=False, verbose_name='Respiratorias')),
                ('fam_respiratorias_cual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cual?')),
                ('fam_desangre', models.BooleanField(default=False, verbose_name='De la sangre')),
                ('fam_desangre_cual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cual?')),
                ('fam_otras', models.BooleanField(blank=True, default=False, null=True, verbose_name='Otras')),
                ('fam_otras_cual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cual?')),
                ('fam_obs', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Antecedentes Familiares',
                'verbose_name_plural': 'Antecedentes Familiares',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AntPersonales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per_cardiologica', models.BooleanField(default=False, verbose_name='Cardiológicas')),
                ('per_cardiologica_cual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cual?')),
                ('per_respiratoria', models.BooleanField(default=False, verbose_name='Respiratorias')),
                ('per_respiratoria_cual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cual?')),
                ('per_neurologicas', models.BooleanField(default=False, verbose_name='Neurológicas')),
                ('per_neurologicas_cual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cual?')),
                ('per_infecciosas', models.BooleanField(default=False, verbose_name='Infecciosas')),
                ('per_infecciosas_cual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cual?')),
                ('per_cirugias', models.BooleanField(default=False, verbose_name='Cirugías')),
                ('per_cirugias_cual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cual?')),
                ('per_alergias', models.BooleanField(default=False, verbose_name='Alergias')),
                ('per_alergias_cual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cual?')),
                ('per_traumatologicas', models.BooleanField(default=False, verbose_name='Traumatológicas')),
                ('per_traumatologicas_cual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cual?')),
                ('per_otras', models.BooleanField(default=False, verbose_name='Otras')),
                ('per_otras_cual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cual?')),
                ('medicacion', models.BooleanField(default=False, verbose_name='Toma alguna medicación')),
                ('medicacion_cual', models.CharField(blank=True, max_length=30, null=True, verbose_name='Cual?')),
                ('medicacion_dosis', models.CharField(blank=True, max_length=30, null=True, verbose_name='Qué dosis?')),
                ('fuma', models.BooleanField(default=False, verbose_name='Fuma?')),
                ('alcohol', models.BooleanField(default=False, verbose_name='Toma alcohol?')),
                ('sustancias', models.BooleanField(default=False, verbose_name='Abuso de sustancias?')),
            ],
            options={
                'verbose_name': 'Antecedentes Personales',
                'verbose_name_plural': 'Antecedentes Personales',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Deporte')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Deporte',
                'verbose_name_plural': 'Deportes',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_general', models.CharField(max_length=40, verbose_name='Estado general')),
                ('talla', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Talla (mts)')),
                ('peso', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='Peso (kg)')),
                ('presion_arterial', models.CharField(max_length=10, verbose_name='TA')),
                ('frecuencia_cardiaca', models.CharField(max_length=10, verbose_name='FC')),
                ('oxigeno_sangre', models.IntegerField(verbose_name='SO2')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=30, null=True, verbose_name='Dirección')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('mail', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Institución',
                'verbose_name_plural': 'Instituciones',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(blank=True, null=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='mail',
            field=models.EmailField(blank=True, max_length=35, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=20, verbose_name='Apellido')),
                ('nombres', models.CharField(max_length=30, verbose_name='Nombres')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('domicilio', models.CharField(blank=True, max_length=30, null=True, verbose_name='Domicilio')),
                ('telefono', models.IntegerField(blank=True, null=True, verbose_name='Teléfono')),
                ('obra_social', models.CharField(blank=True, max_length=25, null=True, verbose_name='Obra Social')),
                ('id_deporte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.deporte')),
                ('id_institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.institucion')),
            ],
            options={
                'verbose_name': 'Deportista',
                'verbose_name_plural': 'Deportistas',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Apto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('A', 'APTO sin restricciones'), ('B', 'AUTORIZADO con recomendación de evaluación y/o tratamiento médico'), ('C', 'NO AUTORIZADO hasta completar la evaluación, tratamiento y/o rehabilitación')], max_length=2, verbose_name='Tipo de Apto')),
                ('observaciones', models.CharField(blank=True, max_length=80, null=True, verbose_name='Observaciones')),
                ('id_familiares', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.antfamiliares')),
                ('id_personales', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.antpersonales')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('id_deportista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.deportista')),
                ('id_examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.examenfisico')),
            ],
            options={
                'verbose_name': 'Apto',
                'verbose_name_plural': 'Aptos',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
