# Generated by Django 5.0.4 on 2024-05-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_antfamiliares_antpersonales_deporte_examenfisico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apto',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
