# Generated by Django 5.0.4 on 2024-05-28 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_apto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
