# Generated by Django 5.0.4 on 2024-05-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_institucion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='mail',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Correo Electrónico'),
        ),
    ]
