# Generated by Django 5.0.4 on 2024-06-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_usuario_foto_usuario_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_matricula',
            field=models.CharField(blank=True, choices=[(1, 'M.N.'), (2, 'M.P.')], max_length=4, null=True, verbose_name='Matrícula'),
        ),
    ]
