# Generated by Django 4.2.13 on 2024-06-30 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_apto_id_familiares_remove_apto_id_personales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='evaluacion_file',
        ),
    ]
