# Generated by Django 4.2.13 on 2024-06-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_evaluacion_evaluacion_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='alcohol',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Toma alcohol?'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fam_cardiovasculares',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cardiovasculares'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fam_desangre',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='De la sangre'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fam_neurologicas',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Neurológicas'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fam_respiratorias',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Respiratorias'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fam_tumorales',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Tumorales'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fuma',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Fuma?'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='medicacion',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Toma alguna medicación'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='per_alergias',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='per_cardiologica',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cardiológicas'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='per_cirugias',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cirugías'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='per_infecciosas',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Infecciosas'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='per_neurologicas',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Neurológicas'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='per_otras',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Otras'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='per_respiratoria',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Respiratorias'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='per_traumatologicas',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Traumatológicas'),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='sustancias',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Abuso de sustancias?'),
        ),
    ]
